### ISSUE TITLE
`asdf` install not on PATH

### ISSUE THREAD

**Issue by jamesstidard** [sobolevn/dotbot-asdf#5]
Hi,

I've written a dotfiles configuration that installs `asdf` and then declares the `doubt-asdf` configuration. My initial install will always fail however because the newly installed `asdf` isn't available on the machine's `PATH` and updates made during the configuration script don't appear to effect things executed later. I made a ticket about this on the [dotbot issues](https://github.com/anishathalye/dotbot/issues/207) to look for suggestions.

I was wondering if you happened to know a way to get around this.

Thanks.

**Comment by sobolevn** [comment]
Sorry, I don't know any solutions. Let's wait for the upstream issue.

Thanks for raising this!
